type PlayerType = {
	name: string;
	photo: string;
	age: number;
	nationality: string;
	position: string;
	key?: string;
	_id?: string;
	updatePage?: string;
	leagueGoals?: number;
	cupGoals?: number;
	uclGoals?: number;
	totalGoals?: number;
	leagueGames?: number;
	cupGames?: number;
	uclGames?: number;
	totalGames?: number;
	leagueAssists?: number;
	cupAssists?: number;
	uclAssists?: number;
	totalAssists?: number;
	leagueContributions?: number;
	cupContributions?: number;
	uclContributions?: number;
	totalContributions?: number;
	goalsPerGame?: number;
	assistsPerGame?: number;
	contributionsPerGame?: number;
	cleanSheets?: number;
	cleanSheetsPerGame?: number;
	hattricks?: number;
	seasons?: Array<number>;
	shirtNumbers?: Array<number>;
	yellowCards?: number;
	redCards?: number;
	rating?: number;
};

export default PlayerType;
